import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const binDir = resolve(root, "rtlsdr-bin");
const outFile = resolve(root, "src", "_embedded-bins.ts");

const files = ["rtl_fm.exe", "librtlsdr.dll"];

let code = `// Auto-generated by scripts/embed-bins.mjs — do not edit\n`;

for (const f of files) {
  const buf = readFileSync(resolve(binDir, f));
  code += `export const ${f.replace(/[.-]/g, "_").toUpperCase()} = ${JSON.stringify(buf.toString("base64"))};\n`;
}

writeFileSync(outFile, code);
console.log(`Wrote ${outFile} (${files.map(f => f).join(", ")})`);
