export type StateLaw = {
  code: string;
  name: string;
  licensing: string;
  trainingHours: string;
  minAge: string;
  useOfForce: string;
  citizensArrest: string;
  weapons: string;
  agency: string;
  agencyUrl?: string;
  notes: string;
  statutes?: string;
  statuteUrl?: string;
  links?: { text: string; url: string }[];
};

export const STATE_LAWS: StateLaw[] = [
  { code:"AL", name:"Alabama", licensing:"No state license required, but may need local permits", trainingHours:"No mandatory state training", minAge:"19 years old", useOfForce:"Follow general self-defense laws. Force only for self-defense or defense of others.", citizensArrest:"Allowed for felonies committed in presence. Must immediately deliver to law enforcement.", weapons:"Firearms require separate permit. Contact local sheriff.", agency:"Alabama Board of Private Security", agencyUrl:"https://asrb.alabama.gov/", notes:"Requirements vary by county. Check with local law enforcement." },
  { code:"AK", name:"Alaska", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"May use reasonable force for self-defense. Duty to retreat if safely possible.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need separate licensing", agency:"Alaska Department of Public Safety", agencyUrl:"https://dps.alaska.gov/statewide/r-i/permitslicensing/securityguard", notes:"Employers may have their own training requirements." },
  { code:"AZ", name:"Arizona", licensing:"Registration required through DPS", trainingHours:"8 hours pre-assignment, 16 hours within first 6 months", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies in presence or reasonable belief.", weapons:"Armed guards need additional certification", agency:"Arizona Department of Public Safety - Licensing Unit", agencyUrl:"https://www.azdps.gov/services/public-services-center/sgpi-licensing", notes:"Fingerprint clearance card required. Background check mandatory.", statutes:"A.R.S. § 32-2601 et seq.", statuteUrl:"https://www.azleg.gov/arsDetail/?title=32&chapter=26" },
  { code:"AR", name:"Arkansas", licensing:"License required through Arkansas State Police", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Arkansas State Police - Regulatory Services", agencyUrl:"https://dps.arkansas.gov/law-enforcement/arkansas-state-police/services-programs/private-investigators-security-companies-alarm-installation-monitoring/", notes:"Background check required. License must be renewed.", statutes:"Arkansas Code § 17-40-101 et seq.", statuteUrl:"https://www.dps.arkansas.gov/wp-content/uploads/2020/05/Private-security.pdf" },
  { code:"CA", name:"California", licensing:"Guard Card (Guard Registration) required from BSIS", trainingHours:"40 hours (8 hours pre-assignment, 32 hours within first 30 days)", minAge:"18 years old", useOfForce:"Reasonable force for self-defense only. Duty to retreat when safe.", citizensArrest:"Allowed for public offenses committed in presence or felonies.", weapons:"Exposed firearms permit or concealed weapons permit required", agency:"Bureau of Security and Investigative Services (BSIS)", agencyUrl:"https://www.bsis.ca.gov/", notes:"Very strict regulations. Background check and fingerprinting required. Annual renewal.", statutes:"California Business and Professions Code §§ 7580-7599", statuteUrl:"https://www.bsis.ca.gov/about/laws_regs.html" },
  { code:"CO", name:"Colorado", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards may need local permits", agency:"Local jurisdictions regulate security", notes:"No state-level regulation. Check local city/county requirements.", statutes:"No state statute - locally regulated" },
  { code:"CT", name:"Connecticut", licensing:"Security Officer License required", trainingHours:"8 hours pre-assignment", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need special permit", agency:"Connecticut Department of Emergency Services and Public Protection", agencyUrl:"https://portal.ct.gov/despp/Division-of-State-Police/Special-Licensing-and-Firearms/Private-Security-Companies", notes:"Background check and fingerprinting required.", statutes:"Connecticut General Statutes § 29-161a et seq.", statuteUrl:"https://www.cga.ct.gov/current/pub/chap_534.htm" },
  { code:"DE", name:"Delaware", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"Delaware State Police", notes:"Individual employers set training requirements." },
  { code:"FL", name:"Florida", licensing:"Class D Security Officer License required", trainingHours:"40 hours (Class D training)", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Class G license required for armed guards", agency:"Florida Department of Agriculture - Division of Licensing", agencyUrl:"https://www.fdacs.gov/Business-Services/Private-Security-Licenses", notes:"Background check required. License valid for 2 years. Continuing education required.", statutes:"Florida Statutes Chapter 493", statuteUrl:"http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0400-0499/0493/0493.html" },
  { code:"GA", name:"Georgia", licensing:"Registration required with Georgia Board of Private Detective and Security Agencies", trainingHours:"No specific state requirement, but employers must provide training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies in presence or immediate knowledge.", weapons:"Firearms license required for armed guards", agency:"Georgia Board of Private Detective and Security Agencies", agencyUrl:"https://sos.ga.gov/board-private-detective-and-security-agencies", notes:"Background check required. Must be registered before working.", statutes:"O.C.G.A. § 43-38", statuteUrl:"https://sos.ga.gov/page/private-detective-and-security-agency-rules-and-regulations" },
  { code:"HI", name:"Hawaii", licensing:"Guard registration required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Strict firearms regulations", agency:"Hawaii Board of Private Detectives and Guards", agencyUrl:"https://cca.hawaii.gov/pvl/boards/private/", notes:"Background check required. Registration must be renewed.", statutes:"Hawaii Revised Statutes Chapter 463", statuteUrl:"https://www.capitol.hawaii.gov/hrscurrent/Vol10_Ch0436-0474/HRS0463/" },
  { code:"ID", name:"Idaho", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards may need permits", agency:"No state regulatory agency", notes:"Employer-based training and requirements." },
  { code:"IL", name:"Illinois", licensing:"PERC (Permanent Employee Registration Card) required", trainingHours:"20 hours pre-assignment", minAge:"18 years old (21 for armed)", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"FOID card and additional licensing for armed guards", agency:"Illinois Department of Financial and Professional Regulation", agencyUrl:"https://idfpr.illinois.gov/profs/securitycont.html", notes:"Background check and fingerprinting required. Annual renewal.", statutes:"225 ILCS 447 (Private Detective, Private Alarm, Private Security Act)", statuteUrl:"https://idfpr.illinois.gov/profs/securitycont.html" },
  { code:"IN", name:"Indiana", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"IA", name:"Iowa", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need professional permit", agency:"Iowa Department of Public Safety", notes:"Employers may require training.", statutes:"Iowa Code Chapter 80A (armed guards only)", statuteUrl:"https://www.legis.iowa.gov/law/iowaCode/sections?codeChapter=80A" },
  { code:"KS", name:"Kansas", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"KY", name:"Kentucky", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need CCDW license", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set training standards." },
  { code:"LA", name:"Louisiana", licensing:"Security Officer Commission required", trainingHours:"8 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Louisiana State Board of Private Security Examiners", agencyUrl:"https://www.lsbpse.com/", notes:"Background check required. Commission must be renewed annually.", statutes:"Louisiana Revised Statutes Title 37, Chapter 25", statuteUrl:"https://legis.la.gov/legis/Laws_Toc.aspx?folder=78&title=37" },
  { code:"ME", name:"Maine", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"MD", name:"Maryland", licensing:"Security Guard License required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Special licensing for armed guards", agency:"Maryland State Police - Licensing Division", agencyUrl:"https://mdsp.maryland.gov/Organization/Pages/CriminalInvestigationBureau/LicensingDivision.aspx", notes:"Background check required. License must be renewed.", statutes:"Maryland Business Occupations and Professions Code § 19-101 et seq.", statuteUrl:"https://mdsp.maryland.gov/Organization/Pages/CriminalInvestigationBureau/LicensingDivision/ProfessionalLicenses.aspx" },
  { code:"MA", name:"Massachusetts", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"FID card required for armed guards", agency:"Local police departments", notes:"Regulated at local level. Check with local police." },
  { code:"MI", name:"Michigan", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Michigan State Police", notes:"Individual employers may require training and certification." },
  { code:"MN", name:"Minnesota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Minnesota Board of Private Detective and Protective Agent Services", agencyUrl:"https://dps.mn.gov/about-dps/associated-boards-cmtes-and-task-forces/private-detective-and-protective-agents-board", notes:"Employers must be licensed, but individual guards are not.", statutes:"Minnesota Statutes Chapter 326", statuteUrl:"https://www.revisor.mn.gov/statutes/cite/326" },
  { code:"MS", name:"Mississippi", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"MO", name:"Missouri", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"MT", name:"Montana", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"Montana Board of Private Security", agencyUrl:"https://boards.bsd.dli.mt.gov/private-security/", notes:"Employers must be licensed, individual guards are not.", statutes:"Montana Code Annotated Title 37, Chapter 60", statuteUrl:"https://leg.mt.gov/bills/mca/title_0370/chapter_0600/parts_index.html" },
  { code:"NE", name:"Nebraska", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need permits", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"NV", name:"Nevada", licensing:"Work Card required from Private Investigators Licensing Board", trainingHours:"8 hours pre-assignment", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Firearms endorsement required for armed guards", agency:"Nevada Private Investigators Licensing Board", agencyUrl:"https://pilb.nv.gov/", notes:"Background check and fingerprinting required.", statutes:"Nevada Revised Statutes Chapter 648", statuteUrl:"https://www.leg.state.nv.us/nrs/NRS-648.html" },
  { code:"NH", name:"New Hampshire", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"NJ", name:"New Jersey", licensing:"SORA (Security Officer Registration Act) Card required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and indictable offenses in presence.", weapons:"Firearms permit required for armed guards", agency:"New Jersey State Police", agencyUrl:"https://www.njsp.org/private-detective/", notes:"Background check and fingerprinting required.", statutes:"N.J.S.A. 45:19A-1 et seq.", statuteUrl:"https://www.nj.gov/njsp/info/pdf/pdet/sora-faq.pdf" },
  { code:"NM", name:"New Mexico", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"New Mexico Regulation and Licensing Department", agencyUrl:"https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/private-investigations-security-guard/", notes:"Employer-based requirements." },
  { code:"NY", name:"New York", licensing:"Security Guard Registration required", trainingHours:"8 hours pre-assignment, 16 hours on-the-job training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and certain misdemeanors in presence.", weapons:"Special armed guard registration required", agency:"New York Department of State - Division of Licensing Services", agencyUrl:"https://dos.ny.gov/security-guard", notes:"Background check required. Training must be approved by NYS.", statutes:"New York General Business Law Article 7-A", statuteUrl:"https://dos.ny.gov/security-guard" },
  { code:"NC", name:"North Carolina", licensing:"Registration required with Private Protective Services Board", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need additional certification", agency:"North Carolina Private Protective Services Board", agencyUrl:"https://www.ncdps.gov/about-dps/boards-and-commissions/private-protective-services-board", notes:"Background check required. Must register before employment.", statutes:"N.C.G.S. Chapter 74C", statuteUrl:"https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_74C.html" },
  { code:"ND", name:"North Dakota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"North Dakota Private Investigation and Security Board", agencyUrl:"https://www.pisb.nd.gov/", notes:"Employers must be licensed, individual guards are not.", statutes:"North Dakota Century Code Chapter 43-30", statuteUrl:"https://ndlegis.gov/cencode/t43c30.pdf" },
  { code:"OH", name:"Ohio", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Ohio Department of Public Safety", notes:"Local jurisdictions may have additional requirements." },
  { code:"OK", name:"Oklahoma", licensing:"Security Guard License required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional licensing", agency:"Oklahoma CLEET", agencyUrl:"https://oklahoma.gov/cleet/licensing/security-guard.html", notes:"Background check required. License must be renewed.", statutes:"Oklahoma Statutes Title 59, Section 1750.1 et seq.", statuteUrl:"https://oklahoma.gov/cleet/licensing.html" },
  { code:"OR", name:"Oregon", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Oregon Department of Public Safety Standards and Training", agencyUrl:"https://www.oregon.gov/dpsst/pages/default.aspx", notes:"Employer-based requirements." },
  { code:"PA", name:"Pennsylvania", licensing:"Act 235 certification NOT required for unarmed guards", trainingHours:"No state requirement for unarmed guards", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Act 235 certification required for armed guards (40 hours)", agency:"Pennsylvania State Police", agencyUrl:"https://www.pa.gov/agencies/psp/programs/law-enforcement-training/lethal-weapons-training-program", notes:"Act 235 only required if carrying a weapon on duty.", statutes:"Act 235 of 1974 (Lethal Weapons Training Act)", statuteUrl:"https://www.legis.state.pa.us/WU01/LI/LI/US/HTM/1974/0/0235..HTM" },
  { code:"RI", name:"Rhode Island", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"SC", name:"South Carolina", licensing:"Security Guard/Patrol License required", trainingHours:"4 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"South Carolina Law Enforcement Division (SLED)", agencyUrl:"https://www.sled.sc.gov/", notes:"Background check required. License must be renewed every 2 years.", statutes:"South Carolina Code § 40-18-10 et seq.", statuteUrl:"https://www.scstatehouse.gov/code/t40c018.php" },
  { code:"SD", name:"South Dakota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"TN", name:"Tennessee", licensing:"Security Guard/Officer License required", trainingHours:"8 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Tennessee Department of Commerce and Insurance", agencyUrl:"https://www.tn.gov/commerce/licensing-regulations/private-protective-services.html", notes:"Background check required. License must be renewed annually.", statutes:"Tennessee Code Annotated § 62-35-101 et seq.", statuteUrl:"https://www.tn.gov/commerce/licensing-regulations/private-protective-services.html" },
  { code:"TX", name:"Texas", licensing:"Level II (Non-Commissioned Security Officer) or higher required", trainingHours:"6 hours classroom, 4 hours on-the-job", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Level III or IV required for armed guards", agency:"Texas Department of Public Safety - Private Security Bureau", agencyUrl:"https://www.dps.texas.gov/section/private-security", notes:"Background check required. License must be renewed every 2 years.", statutes:"Texas Occupations Code Chapter 1702", statuteUrl:"https://statutes.capitol.texas.gov/Docs/OC/htm/OC.1702.htm" },
  { code:"UT", name:"Utah", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need Bureau of Criminal Identification approval", agency:"Utah Bureau of Criminal Identification", agencyUrl:"https://bci.utah.gov/", notes:"Employer-based requirements." },
  { code:"VT", name:"Vermont", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"VA", name:"Virginia", licensing:"Registration required with DCJS", trainingHours:"Entry-level training (18 hours minimum) + in-service training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed certification requires additional training", agency:"Virginia Department of Criminal Justice Services (DCJS)", agencyUrl:"https://www.dcjs.virginia.gov/private-security-organization/private-security", notes:"Compulsory minimum training standards. Background check required.", statutes:"Code of Virginia § 9.1-138 et seq.", statuteUrl:"https://law.lis.virginia.gov/vacodefull/title9.1/chapter1/article4/" },
  { code:"WA", name:"Washington", licensing:"Security Guard License required", trainingHours:"8 hours pre-assignment, additional training within 14 days", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guard license requires additional training", agency:"Washington Department of Licensing", agencyUrl:"https://dol.wa.gov/", notes:"Background check and fingerprinting required. Annual renewal.", statutes:"RCW 18.170 - Private Security Guards", statuteUrl:"https://app.leg.wa.gov/rcw/default.aspx?Cite=18.170" },
  { code:"WV", name:"West Virginia", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"WI", name:"Wisconsin", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"WY", name:"Wyoming", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
];
