export type StateLaw = {
  code: string;
  name: string;
  licensing: string;
  trainingHours: string;
  minAge: string;
  useOfForce: string;
  citizensArrest: string;
  weapons: string;
  agency: string;
  notes: string;
  statutes?: string;
  links?: { text: string; url: string }[];
};

export const STATE_LAWS: StateLaw[] = [
  { code:"AL", name:"Alabama", licensing:"No state license required, but may need local permits", trainingHours:"No mandatory state training", minAge:"19 years old", useOfForce:"Follow general self-defense laws. Force only for self-defense or defense of others.", citizensArrest:"Allowed for felonies committed in presence. Must immediately deliver to law enforcement.", weapons:"Firearms require separate permit. Contact local sheriff.", agency:"Alabama Board of Private Security", notes:"Requirements vary by county. Check with local law enforcement." },
  { code:"AK", name:"Alaska", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"May use reasonable force for self-defense. Duty to retreat if safely possible.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need separate licensing", agency:"Alaska Department of Public Safety", notes:"Employers may have their own training requirements." },
  { code:"AZ", name:"Arizona", licensing:"Registration required through DPS", trainingHours:"8 hours pre-assignment, 16 hours within first 6 months", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies in presence or reasonable belief.", weapons:"Armed guards need additional certification", agency:"Arizona Department of Public Safety - Licensing Unit", notes:"Fingerprint clearance card required. Background check mandatory." },
  { code:"AR", name:"Arkansas", licensing:"License required through Arkansas State Police", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Arkansas State Police - Regulatory Services", notes:"Background check required. License must be renewed.", statutes:"Arkansas Code § 17-40-101 et seq." },
  { code:"CA", name:"California", licensing:"Guard Card (Guard Registration) required from BSIS", trainingHours:"40 hours (8 hours pre-assignment, 32 hours within first 30 days)", minAge:"18 years old", useOfForce:"Reasonable force for self-defense only. Duty to retreat when safe.", citizensArrest:"Allowed for public offenses committed in presence or felonies.", weapons:"Exposed firearms permit or concealed weapons permit required", agency:"Bureau of Security and Investigative Services (BSIS)", notes:"Very strict regulations. Background check and fingerprinting required. Annual renewal." },
  { code:"CO", name:"Colorado", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards may need local permits", agency:"Local jurisdictions regulate security", notes:"No state-level regulation. Check local city/county requirements.", statutes:"No state statute - locally regulated" },
  { code:"CT", name:"Connecticut", licensing:"Security Officer License required", trainingHours:"8 hours pre-assignment", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need special permit", agency:"Connecticut Department of Emergency Services and Public Protection", notes:"Background check and fingerprinting required.", statutes:"Connecticut General Statutes § 29-161a et seq." },
  { code:"DE", name:"Delaware", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"Delaware State Police", notes:"Individual employers set training requirements." },
  { code:"FL", name:"Florida", licensing:"Class D Security Officer License required", trainingHours:"40 hours (Class D training)", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Class G license required for armed guards", agency:"Florida Department of Agriculture - Division of Licensing", notes:"Background check required. License valid for 2 years. Continuing education required." },
  { code:"GA", name:"Georgia", licensing:"Registration required with Georgia Board of Private Detective and Security Agencies", trainingHours:"No specific state requirement, but employers must provide training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies in presence or immediate knowledge.", weapons:"Firearms license required for armed guards", agency:"Georgia Board of Private Detective and Security Agencies", notes:"Background check required. Must be registered before working." },
  { code:"HI", name:"Hawaii", licensing:"Guard registration required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Strict firearms regulations", agency:"Hawaii Board of Private Detectives and Guards", notes:"Background check required. Registration must be renewed.", statutes:"Hawaii Revised Statutes Chapter 463" },
  { code:"ID", name:"Idaho", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards may need permits", agency:"No state regulatory agency", notes:"Employer-based training and requirements." },
  { code:"IL", name:"Illinois", licensing:"PERC (Permanent Employee Registration Card) required", trainingHours:"20 hours pre-assignment", minAge:"18 years old (21 for armed)", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"FOID card and additional licensing for armed guards", agency:"Illinois Department of Financial and Professional Regulation", notes:"Background check and fingerprinting required. Annual renewal." },
  { code:"IN", name:"Indiana", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"IA", name:"Iowa", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need professional permit", agency:"Iowa Department of Public Safety", notes:"Employers may require training.", statutes:"Iowa Code Chapter 80A (armed guards only)" },
  { code:"KS", name:"Kansas", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"KY", name:"Kentucky", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need CCDW license", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set training standards." },
  { code:"LA", name:"Louisiana", licensing:"Security Officer Commission required", trainingHours:"8 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Louisiana State Board of Private Security Examiners", notes:"Background check required. Commission must be renewed annually.", statutes:"Louisiana Revised Statutes Title 37, Chapter 25" },
  { code:"ME", name:"Maine", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"MD", name:"Maryland", licensing:"Security Guard License required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Special licensing for armed guards", agency:"Maryland State Police - Licensing Division", notes:"Background check required. License must be renewed.", statutes:"Maryland Business Occupations and Professions Code § 19-101 et seq." },
  { code:"MA", name:"Massachusetts", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"FID card required for armed guards", agency:"Local police departments", notes:"Regulated at local level. Check with local police." },
  { code:"MI", name:"Michigan", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Michigan State Police", notes:"Individual employers may require training and certification." },
  { code:"MN", name:"Minnesota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Minnesota Board of Private Detective and Protective Agent Services", notes:"Employers must be licensed, but individual guards are not.", statutes:"Minnesota Statutes Chapter 326" },
  { code:"MS", name:"Mississippi", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"MO", name:"Missouri", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"MT", name:"Montana", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"Montana Board of Private Security", notes:"Employers must be licensed, individual guards are not.", statutes:"Montana Code Annotated Title 37, Chapter 60" },
  { code:"NE", name:"Nebraska", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need permits", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"NV", name:"Nevada", licensing:"Work Card required from Private Investigators Licensing Board", trainingHours:"8 hours pre-assignment", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Firearms endorsement required for armed guards", agency:"Nevada Private Investigators Licensing Board", notes:"Background check and fingerprinting required.", statutes:"Nevada Revised Statutes Chapter 648" },
  { code:"NH", name:"New Hampshire", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"NJ", name:"New Jersey", licensing:"SORA (Security Officer Registration Act) Card required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and indictable offenses in presence.", weapons:"Firearms permit required for armed guards", agency:"New Jersey State Police", notes:"Background check and fingerprinting required.", statutes:"N.J.S.A. 45:19A-1 et seq." },
  { code:"NM", name:"New Mexico", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"New Mexico Regulation and Licensing Department", notes:"Employer-based requirements." },
  { code:"NY", name:"New York", licensing:"Security Guard Registration required", trainingHours:"8 hours pre-assignment, 16 hours on-the-job training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies and certain misdemeanors in presence.", weapons:"Special armed guard registration required", agency:"New York Department of State - Division of Licensing Services", notes:"Background check required. Training must be approved by NYS." },
  { code:"NC", name:"North Carolina", licensing:"Registration required with Private Protective Services Board", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed guards need additional certification", agency:"North Carolina Private Protective Services Board", notes:"Background check required. Must register before employment." },
  { code:"ND", name:"North Dakota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"North Dakota Private Investigation and Security Board", notes:"Employers must be licensed, individual guards are not.", statutes:"North Dakota Century Code Chapter 43-30" },
  { code:"OH", name:"Ohio", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Ohio Department of Public Safety", notes:"Local jurisdictions may have additional requirements." },
  { code:"OK", name:"Oklahoma", licensing:"Security Guard License required", trainingHours:"No specific state requirement", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional licensing", agency:"Oklahoma CLEET", notes:"Background check required. License must be renewed.", statutes:"Oklahoma Statutes Title 59, Section 1750.1 et seq." },
  { code:"OR", name:"Oregon", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need separate licensing", agency:"Oregon Department of Public Safety Standards and Training", notes:"Employer-based requirements." },
  { code:"PA", name:"Pennsylvania", licensing:"Act 235 certification NOT required for unarmed guards", trainingHours:"No state requirement for unarmed guards", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Act 235 certification required for armed guards (40 hours)", agency:"Pennsylvania State Police", notes:"Act 235 only required if carrying a weapon on duty." },
  { code:"RI", name:"Rhode Island", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"SC", name:"South Carolina", licensing:"Security Guard/Patrol License required", trainingHours:"4 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"South Carolina Law Enforcement Division (SLED)", notes:"Background check required. License must be renewed every 2 years.", statutes:"South Carolina Code § 40-18-10 et seq." },
  { code:"SD", name:"South Dakota", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"TN", name:"Tennessee", licensing:"Security Guard/Officer License required", trainingHours:"8 hours minimum", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need additional certification", agency:"Tennessee Department of Commerce and Insurance", notes:"Background check required. License must be renewed annually.", statutes:"Tennessee Code Annotated § 62-35-101 et seq." },
  { code:"TX", name:"Texas", licensing:"Level II (Non-Commissioned Security Officer) or higher required", trainingHours:"6 hours classroom, 4 hours on-the-job", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Level III or IV required for armed guards", agency:"Texas Department of Public Safety - Private Security Bureau", notes:"Background check required. License must be renewed every 2 years." },
  { code:"UT", name:"Utah", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards need Bureau of Criminal Identification approval", agency:"Utah Bureau of Criminal Identification", notes:"Employer-based requirements." },
  { code:"VT", name:"Vermont", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"VA", name:"Virginia", licensing:"Registration required with DCJS", trainingHours:"Entry-level training (18 hours minimum) + in-service training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies and breaches of peace in presence.", weapons:"Armed certification requires additional training", agency:"Virginia Department of Criminal Justice Services (DCJS)", notes:"Compulsory minimum training standards. Background check required." },
  { code:"WA", name:"Washington", licensing:"Security Guard License required", trainingHours:"8 hours pre-assignment, additional training within 14 days", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Duty to retreat when safe.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guard license requires additional training", agency:"Washington Department of Licensing", notes:"Background check and fingerprinting required. Annual renewal.", statutes:"RCW 18.170 - Private Security Guards" },
  { code:"WV", name:"West Virginia", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
  { code:"WI", name:"Wisconsin", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency for unarmed guards", notes:"Individual employers set requirements." },
  { code:"WY", name:"Wyoming", licensing:"No state license required for unarmed guards", trainingHours:"No mandatory state training", minAge:"18 years old", useOfForce:"Reasonable force for self-defense. Stand your ground law applies.", citizensArrest:"Allowed for felonies committed in presence.", weapons:"Armed guards regulated separately", agency:"No state regulatory agency", notes:"Employer-based requirements." },
];
