-- COMPLETE MIGRATION: Modules 3-5 Assessment Questions
-- This migrates questions for modules 3-5 from student-portal.js
-- Run this AFTER running add-questions-json-column.sql and the previous migrations

-- Using dollar-quote syntax ($$) to avoid escaping issues with single quotes

-- ============================================================================
-- MODULE 3: THREAT ASSESSMENT & SITUATIONAL AWARENESS (20 questions)
-- ============================================================================
UPDATE assessments
SET questions_json = $$[
    {"question": "What is situational awareness?", "options": ["Being aware of your schedule and appointments", "The ability to identify, process, and comprehend critical information about your environment", "Knowing where all exits are located", "Watching security cameras constantly"], "correctAnswer": 1, "explanation": "Situational awareness is the ability to identify, process, and comprehend critical information about your environment."},
    {"question": "In Cooper's Color Codes, what does \"Condition Yellow\" mean?", "options": ["Unaware of surroundings - avoid this state", "Relaxed alert - aware of surroundings, no specific threats (normal for security)", "Specific threat identified, assessing options", "Immediate threat, taking action"], "correctAnswer": 1, "explanation": "Condition Yellow is relaxed alert - aware of surroundings with no specific threats."},
    {"question": "What is de-escalation?", "options": ["Using force to control a situation", "Techniques used to prevent a situation from escalating to violence", "Calling for backup immediately", "Removing yourself from any conflict"], "correctAnswer": 1, "explanation": "De-escalation uses techniques to prevent situations from escalating to violence."},
    {"question": "The \"21-Foot Rule\" states that:", "options": ["You must stay 21 feet away from all threats", "A person with a knife can close 21 feet in about 1.5 seconds", "You should maintain 21 feet of personal space", "Backup must arrive within 21 seconds"], "correctAnswer": 1, "explanation": "A person with a knife can close 21 feet in about 1.5 seconds."},
    {"question": "What does the \"L\" in the LEAPS de-escalation model stand for?", "options": ["Look for weapons", "Listen actively to their concerns", "Leave the area if unsafe", "Lock down the perimeter"], "correctAnswer": 1, "explanation": "L stands for Listen actively to their concerns."},
    {"question": "Which phrase should you AVOID when de-escalating?", "options": ["\"I want to help you\"", "\"Calm down\" or \"Relax\"", "\"I understand this is frustrating\"", "\"Let's work together to find a solution\""], "correctAnswer": 1, "explanation": "Avoid saying 'Calm down' or 'Relax' as it can escalate the situation."},
    {"question": "What is the difference between cover and concealment?", "options": ["There is no difference, they mean the same thing", "Cover stops bullets, concealment only hides you", "Concealment stops bullets, cover only hides you", "Cover is for active shooters, concealment is for fights"], "correctAnswer": 1, "explanation": "Cover stops bullets, concealment only hides you."},
    {"question": "Pre-attack indicators include all of the following EXCEPT:", "options": ["Surveillance of security procedures", "Asking unusual questions about security", "Wearing appropriate clothing for the weather", "Testing security by probing for weaknesses"], "correctAnswer": 2, "explanation": "Wearing appropriate clothing for the weather is normal behavior, not a pre-attack indicator."},
    {"question": "When is de-escalation NOT appropriate?", "options": ["When someone is frustrated or angry", "When a weapon is displayed or there's imminent threat to life", "When someone is intoxicated", "When someone is arguing loudly"], "correctAnswer": 1, "explanation": "De-escalation is not appropriate when there's a weapon or imminent threat to life."},
    {"question": "What is the recommended distance to maintain during a tense interaction?", "options": ["1-2 feet to show you're not afraid", "6-10 feet when possible", "15-20 feet minimum", "As close as needed to hear them"], "correctAnswer": 1, "explanation": "Maintain 6-10 feet when possible during tense interactions."},
    {"question": "The OODA Loop stands for:", "options": ["Observe, Operate, Decide, Act", "Observe, Orient, Decide, Act", "Order, Orient, Deploy, Assess", "Observe, Organize, Defend, Alert"], "correctAnswer": 1, "explanation": "OODA Loop: Observe, Orient, Decide, Act."},
    {"question": "What should you do if de-escalation fails and the situation becomes violent?", "options": ["Continue trying to talk them down", "Disengage if possible, call law enforcement, use only necessary force to protect life", "Immediately use maximum force", "Wait for the person to calm down on their own"], "correctAnswer": 1, "explanation": "Disengage if possible, call law enforcement, and use only necessary force."},
    {"question": "A threat is defined as:", "options": ["Any dangerous situation", "Intent + Capability", "Only physical violence", "Something that scares you"], "correctAnswer": 1, "explanation": "A threat is defined as Intent + Capability."},
    {"question": "What are the 3 stages of the threat assessment cycle?", "options": ["See, Report, Act", "Detection, Evaluation, Response", "Observe, Decide, Execute", "Identify, Contain, Resolve"], "correctAnswer": 1, "explanation": "The 3 stages are Detection, Evaluation, Response."},
    {"question": "What does \"baseline vs. anomaly\" mean?", "options": ["Comparing different security posts", "Knowing normal behavior to spot abnormal behavior", "Measuring crowd sizes", "Checking equipment standards"], "correctAnswer": 1, "explanation": "Knowing normal behavior helps you spot abnormal behavior."},
    {"question": "The risk formula is:", "options": ["Risk = Threat + Vulnerability", "Risk = Threat × Vulnerability × Consequence", "Risk = Threat - Protection", "Risk = Danger × Time"], "correctAnswer": 1, "explanation": "Risk = Threat × Vulnerability × Consequence."},
    {"question": "What is the \"25-50-100 Rule\"?", "options": ["Maximum crowd capacity limits", "Know your 25, 50, and 100-foot environment", "Response time standards", "Radio check intervals"], "correctAnswer": 1, "explanation": "Know your 25, 50, and 100-foot environment."},
    {"question": "Weapon pre-indicators include:", "options": ["Smiling and waving", "Blading body, adjusting waistband, hand near pocket", "Walking slowly", "Making eye contact"], "correctAnswer": 1, "explanation": "Weapon pre-indicators include blading body, adjusting waistband, hand near pocket."},
    {"question": "The Ask-Tell-Command progression means:", "options": ["Always command first to show authority", "Start with asking, escalate to telling, then commanding if needed", "Never ask, only tell and command", "Ask three times before giving up"], "correctAnswer": 1, "explanation": "Start with asking, escalate to telling, then commanding if needed."},
    {"question": "What critical mindset should you have about reporting threats?", "options": ["Only report if you're 100% certain", "You don't have to be right—you just have to speak up", "Wait for someone else to report it", "Never report unless supervisor asks"], "correctAnswer": 1, "explanation": "You don't have to be right—you just have to speak up."}
]$$::jsonb,
total_questions = 20
WHERE assessment_name LIKE '%Threat%' OR assessment_name LIKE '%Situational%';

-- ============================================================================
-- MODULE 4: INTRODUCTION TO ICS-100 (15 questions)
-- ============================================================================
UPDATE assessments
SET questions_json = $$[
    {"question": "What does ICS stand for?", "options": ["Internal Command Structure", "Incident Command System", "Integrated Communications System", "International Crisis Standards"], "correctAnswer": 1, "explanation": "ICS stands for Incident Command System."},
    {"question": "Who has overall authority and responsibility for the incident?", "options": ["Operations Section Chief", "Incident Commander (IC)", "Safety Officer", "Planning Section Chief"], "correctAnswer": 1, "explanation": "The Incident Commander (IC) has overall authority and responsibility."},
    {"question": "What is the ideal span of control in ICS?", "options": ["1-3 people per supervisor", "5 people per supervisor", "10-12 people per supervisor", "As many as needed"], "correctAnswer": 1, "explanation": "The ideal span of control is 5 people per supervisor."},
    {"question": "In which section do security guards typically work?", "options": ["Planning Section", "Operations Section", "Logistics Section", "Finance/Administration Section"], "correctAnswer": 1, "explanation": "Security guards typically work in the Operations Section."},
    {"question": "What is the first thing you must do when arriving at an incident?", "options": ["Start working immediately", "Check in at designated location", "Find the Incident Commander", "Set up your equipment"], "correctAnswer": 1, "explanation": "Always check in at the designated location first."},
    {"question": "How many supervisors should you report to in ICS?", "options": ["As many as assign you tasks", "ONE supervisor only", "Two - one primary and one backup", "The Incident Commander and your Section Chief"], "correctAnswer": 1, "explanation": "You should report to ONE supervisor only (unity of command)."},
    {"question": "What is an Incident Action Plan (IAP)?", "options": ["A plan for your personal actions during the incident", "A plan for managing an incident during an operational period", "A plan for evacuating the area", "A plan for calling additional resources"], "correctAnswer": 1, "explanation": "An IAP is a plan for managing an incident during an operational period."},
    {"question": "What does \"Unified Command\" mean?", "options": ["Everyone follows one commander without question", "Multiple agencies share command authority and develop one plan together", "The military takes over command", "All agencies work independently"], "correctAnswer": 1, "explanation": "Unified Command means multiple agencies share authority and develop one plan together."},
    {"question": "Which ICS form is used as an activity log?", "options": ["ICS 201", "ICS 214", "ICS 205", "ICS 211"], "correctAnswer": 1, "explanation": "ICS 214 is used as an activity log."},
    {"question": "What are the three resource status categories in ICS?", "options": ["Ready, Working, Resting", "Assigned, Available, Out of Service", "Active, Standby, Released", "Deployed, Staged, Demobilized"], "correctAnswer": 1, "explanation": "The three categories are: Assigned, Available, Out of Service."},
    {"question": "What is the purpose of NIMS (National Incident Management System)?", "options": ["To provide military support for incidents", "To enable responders from different jurisdictions to work together", "To replace local emergency plans", "To federalize all emergency response"], "correctAnswer": 1, "explanation": "NIMS enables responders from different jurisdictions to work together."},
    {"question": "During a crowd surge simulation, who should the Incident Commander contact first when law enforcement arrives and starts overriding security orders?", "options": ["The media", "The Liaison Officer to coordinate with law enforcement", "All security personnel directly", "The venue owner"], "correctAnswer": 1, "explanation": "Contact the Liaison Officer to coordinate with law enforcement."},
    {"question": "In the simulation, when multiple radio calls are happening at once during mass panic, what should the IC do?", "options": ["Let everyone talk until they finish", "Turn off the radio", "Regain control by asserting command of the channel", "Switch to a different frequency"], "correctAnswer": 2, "explanation": "The IC should regain control by asserting command of the channel."},
    {"question": "What is the primary purpose of the After Action Review (AAR)?", "options": ["To assign blame for mistakes", "To identify what went well, what failed, and what to do differently", "To write reports for management", "To determine who gets promoted"], "correctAnswer": 1, "explanation": "AAR identifies what went well, what failed, and what to do differently."},
    {"question": "During the simulation, when should security personnel document their activities?", "options": ["Only at the end of the incident", "Never - that's someone else's job", "Throughout the incident using ICS 214 activity logs", "Only if something goes wrong"], "correctAnswer": 2, "explanation": "Document activities throughout the incident using ICS 214 activity logs."}
]$$::jsonb,
total_questions = 15
WHERE assessment_name LIKE '%ICS%';

-- ============================================================================
-- MODULE 5: INTERACTING WITH DIVERSE POPULATIONS (15 questions)
-- ============================================================================
UPDATE assessments
SET questions_json = $$[
    {"question": "What is the primary goal when interacting with a diverse population as a security guard?", "options": ["Treat everyone exactly the same without any accommodations", "Provide professional, respectful service to all individuals regardless of background", "Focus only on people who speak English fluently", "Apply stricter security measures to unfamiliar cultural groups"], "correctAnswer": 1, "explanation": "Provide professional, respectful service to all individuals regardless of background."},
    {"question": "Under the ADA, what questions can you ask about a service animal?", "options": ["What is your disability? and Can I see certification?", "Is this a service animal? and What task is it trained to perform?", "Where did you get the animal? and How much did it cost?", "You cannot ask any questions about service animals"], "correctAnswer": 1, "explanation": "You can ask: Is this a service animal? and What task is it trained to perform?"},
    {"question": "What is implicit bias?", "options": ["Openly stated prejudices that you are aware of", "Unconscious attitudes that affect our actions and decisions", "Company policies about who to screen more carefully", "Legal profiling based on statistical crime data"], "correctAnswer": 1, "explanation": "Implicit bias is unconscious attitudes that affect our actions and decisions."},
    {"question": "How should you handle religious head coverings during security screening?", "options": ["Always require removal for proper security screening", "Respect them and screen without requiring removal when possible", "Only allow them if the person has documentation", "Ask the person to prove their religion is legitimate"], "correctAnswer": 1, "explanation": "Respect them and screen without requiring removal when possible."},
    {"question": "When communicating with someone who has a hearing impairment, you should:", "options": ["Speak louder and exaggerate your mouth movements", "Face the person, speak clearly, and use written notes if needed", "Avoid interacting and find someone else to help them", "Use hand gestures only without speaking at all"], "correctAnswer": 1, "explanation": "Face the person, speak clearly, and use written notes if needed."},
    {"question": "What is racial profiling and why is it prohibited?", "options": ["A legal security technique based on crime statistics", "Basing security decisions on race alone - it is illegal discrimination", "A required practice for high-security venues and events", "Profiling is only illegal if done by law enforcement"], "correctAnswer": 1, "explanation": "Racial profiling is basing security decisions on race alone - it is illegal discrimination."},
    {"question": "How should you interact with someone using a wheelchair?", "options": ["Lean on or touch the wheelchair to be friendly", "Never touch the wheelchair without permission and ensure accessible paths", "Speak to their companion instead of directly to them", "Offer to push them even if they don't ask for help"], "correctAnswer": 1, "explanation": "Never touch the wheelchair without permission and ensure accessible paths."},
    {"question": "What should you do if you witness discrimination or harassment at your venue?", "options": ["Ignore it unless the victim files a formal complaint", "Intervene immediately, support the victim, and report to supervisors", "Only get involved if it becomes physically violent", "Wait until your shift ends to mention it to someone"], "correctAnswer": 1, "explanation": "Intervene immediately, support the victim, and report to supervisors."},
    {"question": "When someone has difficulty speaking English, you should:", "options": ["Speak louder and slower in English until they understand", "Use simple language, gestures, and translation apps when available", "Refuse to help them and direct them to find a translator", "Mock their accent to lighten the mood and reduce tension"], "correctAnswer": 1, "explanation": "Use simple language, gestures, and translation apps when available."},
    {"question": "What is the best approach to cultural differences in personal space?", "options": ["Maintain American standards of personal space with everyone", "Be mindful that personal space norms vary by culture", "Stand as close as possible to show you are friendly", "Avoid interacting with people from different cultures"], "correctAnswer": 1, "explanation": "Be mindful that personal space norms vary by culture."},
    {"question": "How should you address someone whose gender presentation is unclear to you?", "options": ["Guess their gender based on their appearance", "Use the name and pronouns the person requests", "Avoid speaking to them to prevent making a mistake", "Ask invasive questions about their gender identity"], "correctAnswer": 1, "explanation": "Use the name and pronouns the person requests."},
    {"question": "What is behavior-based security?", "options": ["Profiling people based on their ethnic background", "Focusing on suspicious actions rather than appearance", "Treating everyone as a potential threat equally", "Only screening people who look nervous or anxious"], "correctAnswer": 1, "explanation": "Behavior-based security focuses on suspicious actions rather than appearance."},
    {"question": "What does \"Security isn't about sameness—it's about skill in difference\" mean?", "options": ["Everyone should be treated exactly the same way", "Professional service means adapting your approach while maintaining standards", "Different groups require different security standards", "Security should focus only on similarities"], "correctAnswer": 1, "explanation": "Professional service means adapting your approach while maintaining standards."},
    {"question": "When writing a report, which description is appropriate?", "options": ["\"Suspicious Middle Eastern male loitering\"", "\"Male, approximately 30s, pacing near entrance for 15 minutes, repeatedly checking phone\"", "\"He looked like he was up to something\"", "\"Typical troublemaker from that neighborhood\""], "correctAnswer": 1, "explanation": "Use objective, behavior-based descriptions without racial or ethnic identifiers."},
    {"question": "What is the best way to communicate with someone who doesn't speak English?", "options": ["Speak louder until they understand", "Use gestures, simple language, translation apps, or find someone who speaks their language", "Give up and call law enforcement", "Refuse to help them"], "correctAnswer": 1, "explanation": "Use gestures, simple language, translation apps, or find someone who speaks their language."}
]$$::jsonb,
total_questions = 15
WHERE assessment_name LIKE '%Diverse%' OR assessment_name LIKE '%Population%';

-- Verify all modules 3-5
SELECT 
    tm.module_name,
    tm.display_order,
    a.assessment_name,
    a.total_questions,
    jsonb_array_length(a.questions_json) as actual_questions,
    CASE 
        WHEN jsonb_array_length(a.questions_json) = a.total_questions THEN '✓ Match'
        ELSE '✗ Mismatch'
    END as status
FROM assessments a
JOIN training_modules tm ON a.module_id = tm.id
WHERE tm.display_order IN (3, 4, 5)
ORDER BY tm.display_order;
