-- Migrate Comprehensive Guard Certification Assessment (42 questions)
-- This is the final comprehensive exam covering all modules
-- Run this AFTER running add-questions-json-column.sql

-- Using dollar-quote syntax ($$) to avoid escaping issues with single quotes

-- ============================================================================
-- COMPREHENSIVE GUARD CERTIFICATION (42 questions)
-- ============================================================================
-- This assessment covers material from all 7 modules

UPDATE assessments
SET questions_json = $$[
    {"question": "What is the most important responsibility of an event security guard?", "options": ["Looking intimidating to deter potential troublemakers", "Ensuring safety and security of all attendees at the event", "Checking social media for updates about the event", "Selling tickets and helping with merchandise sales"], "correctAnswer": 1, "explanation": "The primary responsibility is ensuring safety and security of all attendees."},
    {"question": "When should you use your radio?", "options": ["For personal conversations with other security staff", "For official security communications and emergencies only", "To play music and entertainment during slow periods", "Never use it to avoid cluttering the channel"], "correctAnswer": 1, "explanation": "Radios are for official security communications and emergencies only."},
    {"question": "What does \"10-4\" mean on the radio?", "options": ["Emergency situation requiring all units to respond", "Message received and understood clearly by recipient", "Out of service and unavailable for assignments", "Need backup assistance at your current location"], "correctAnswer": 1, "explanation": "10-4 means message received and understood."},
    {"question": "If you witness a fight, you should:", "options": ["Join in to help physically separate the individuals", "Call for backup, attempt verbal de-escalation if safe, protect bystanders", "Film it with your phone to capture evidence", "Walk away and let them resolve it themselves"], "correctAnswer": 1, "explanation": "Call for backup, attempt de-escalation if safe, and protect bystanders."},
    {"question": "Professional appearance includes:", "options": ["Wearing whatever you want", "Clean uniform, proper grooming, visible ID", "Casual clothes", "Hiding your badge"], "correctAnswer": 1, "explanation": "Professional appearance includes clean uniform, proper grooming, and visible ID."},
    {"question": "If an attendee is intoxicated and disruptive, you should:", "options": ["Serve them more alcohol", "Assess situation, deny further service, arrange safe removal if needed", "Ignore them", "Laugh at them"], "correctAnswer": 1, "explanation": "Assess the situation, deny further service, and arrange safe removal if needed."},
    {"question": "Chain of command means:", "options": ["Everyone is equal", "Following proper reporting structure and authority levels", "Ignoring supervisors", "Doing whatever you want"], "correctAnswer": 1, "explanation": "Chain of command means following proper reporting structure and authority levels."},
    {"question": "When writing an incident report, you should:", "options": ["Make up details", "Be factual, objective, and include all relevant information", "Exaggerate", "Leave out important facts"], "correctAnswer": 1, "explanation": "Incident reports should be factual, objective, and include all relevant information."},
    {"question": "If you find a suspicious unattended bag, you should:", "options": ["Open it carefully to see what's inside before reporting", "Do not touch it, clear the area, alert supervisor and authorities", "Kick it to a corner out of the way of foot traffic", "Take it home to lost and found after your shift"], "correctAnswer": 1, "explanation": "Do not touch it, clear the area, and alert supervisor and authorities."},
    {"question": "De-escalation techniques include:", "options": ["Yelling louder", "Calm voice, active listening, offering solutions, maintaining distance", "Physical confrontation", "Insults"], "correctAnswer": 1, "explanation": "De-escalation includes calm voice, active listening, offering solutions, and maintaining distance."},
    {"question": "Your post assignment means:", "options": ["You can leave whenever", "You stay at assigned location unless relieved or emergency", "You can wander around", "You can switch with anyone"], "correctAnswer": 1, "explanation": "You stay at your assigned location unless relieved or there's an emergency."},
    {"question": "If you need to leave your post, you must:", "options": ["Just leave", "Get supervisor approval and ensure post is covered", "Tell a friend", "Sneak away"], "correctAnswer": 1, "explanation": "Get supervisor approval and ensure your post is covered."},
    {"question": "Customer service in security means:", "options": ["Being rude to assert authority", "Being helpful, professional, and respectful while enforcing rules", "Ignoring people", "Only helping VIPs"], "correctAnswer": 1, "explanation": "Customer service means being helpful, professional, and respectful while enforcing rules."},
    {"question": "If you see a lost child, you should:", "options": ["Ignore them", "Stay with child, call supervisor, use PA system, reunite with parent safely", "Send them away", "Take them home"], "correctAnswer": 1, "explanation": "Stay with the child, call supervisor, use PA system, and reunite with parent safely."},
    {"question": "Situational awareness means:", "options": ["Staring at your phone to monitor social media", "Being alert to your surroundings and potential threats", "Daydreaming about what you'll do after work", "Closing your eyes periodically to rest and relax"], "correctAnswer": 1, "explanation": "Situational awareness means being alert to your surroundings and potential threats."},
    {"question": "If someone asks for directions, you should:", "options": ["Ignore them", "Provide clear, helpful directions while maintaining security awareness", "Tell them to figure it out", "Give wrong directions"], "correctAnswer": 1, "explanation": "Provide clear, helpful directions while maintaining security awareness."},
    {"question": "What should you do during a shift briefing?", "options": ["Sleep", "Pay attention, take notes, ask questions about your assignment", "Talk to friends", "Leave early"], "correctAnswer": 1, "explanation": "Pay attention, take notes, and ask questions about your assignment."},
    {"question": "If you witness theft, you should:", "options": ["Chase the suspect alone", "Observe and report details to supervisor and police, ensure safety first", "Ignore it", "Tackle them"], "correctAnswer": 1, "explanation": "Observe and report details to supervisor and police, ensuring safety first."},
    {"question": "Proper radio etiquette includes:", "options": ["Interrupting others", "Waiting for clear channel, being concise, using proper codes", "Talking constantly", "Using slang"], "correctAnswer": 1, "explanation": "Wait for clear channel, be concise, and use proper codes."},
    {"question": "If weather becomes severe during an outdoor event, you should:", "options": ["Continue as normal", "Follow emergency weather protocol, help evacuate to shelter if needed", "Run away", "Ignore warnings"], "correctAnswer": 1, "explanation": "Follow emergency weather protocol and help evacuate to shelter if needed."},
    {"question": "Confidentiality means:", "options": ["Posting everything on social media", "Not discussing security details, incidents, or private information publicly", "Telling everyone", "Sharing passwords"], "correctAnswer": 1, "explanation": "Not discussing security details, incidents, or private information publicly."},
    {"question": "If you make a mistake, you should:", "options": ["Hide it", "Report it to supervisor immediately and learn from it", "Blame others", "Lie about it"], "correctAnswer": 1, "explanation": "Report it to supervisor immediately and learn from it."},
    {"question": "Physical force should be used:", "options": ["Whenever you want", "Only as last resort for self-defense or defense of others, within legal limits", "To intimidate people", "Never, even in emergencies"], "correctAnswer": 1, "explanation": "Only as last resort for self-defense or defense of others, within legal limits."},
    {"question": "If you feel unsafe in a situation, you should:", "options": ["Act tough", "Call for backup and prioritize your safety", "Handle it alone", "Ignore your instincts"], "correctAnswer": 1, "explanation": "Call for backup and prioritize your safety."},
    {"question": "End-of-shift procedures include:", "options": ["Just leaving", "Completing reports, briefing relief, returning equipment, signing out", "Disappearing", "Taking equipment home"], "correctAnswer": 1, "explanation": "Complete reports, brief relief, return equipment, and sign out."},
    {"question": "As a security guard, your legal authority comes from:", "options": ["Your security guard license issued by the state", "The property owner's rights to control their property", "Special powers granted by local law enforcement", "Federal regulations governing the private security industry"], "correctAnswer": 1, "explanation": "Your authority comes from the property owner's rights to control their property."},
    {"question": "The first level of the use of force continuum is:", "options": ["Verbal commands and clear directions to subjects", "Officer presence in uniform as a visible deterrent", "Empty hand control techniques for physical guidance", "Defensive tactics when facing immediate physical threats"], "correctAnswer": 1, "explanation": "Officer presence in uniform is the first level of the use of force continuum."},
    {"question": "When can you legally use physical force as a security guard?", "options": ["To enforce company rules and remove trespassers", "Only for self-defense or defense of others from harm", "Whenever someone refuses to follow your commands", "To detain suspects until police arrive on scene"], "correctAnswer": 1, "explanation": "Only for self-defense or defense of others from harm."},
    {"question": "Reasonable force means:", "options": ["Any force necessary to gain compliance from subjects", "Force that is proportional to the threat you face", "The maximum force allowed by your company policy", "Force approved by your supervisor before taking action"], "correctAnswer": 1, "explanation": "Force that is proportional to the threat you face."},
    {"question": "If someone refuses to leave private property, you should:", "options": ["Physically escort them off the property immediately", "Call police and let them handle the removal", "Use reasonable force to drag them to the exit", "Threaten them with arrest if they don't comply"], "correctAnswer": 1, "explanation": "Call police and let them handle the removal."},
    {"question": "Citizen's arrest by security guards is:", "options": ["Recommended for all felonies committed on property", "Not recommended due to high liability risks", "Required by law when you witness a crime", "Only allowed with written permission from employer"], "correctAnswer": 1, "explanation": "Not recommended due to high liability risks."},
    {"question": "Using excessive force can result in:", "options": ["A written warning placed in your employment file", "Criminal charges, civil lawsuits, and license revocation", "Mandatory retraining and probation at your job", "Suspension without pay for up to one week"], "correctAnswer": 1, "explanation": "Criminal charges, civil lawsuits, and license revocation."},
    {"question": "Security guard laws and requirements:", "options": ["Are exactly the same in every state nationwide", "Vary significantly by state and must be researched", "Only apply to armed security guard positions", "Are optional and recommended but not legally required"], "correctAnswer": 1, "explanation": "Vary significantly by state and must be researched."},
    {"question": "What should you do when facing a situation that may require force?", "options": ["Handle it yourself to show competence to supervisors", "Observe, report, and call police to handle it", "Use minimal force and document it thoroughly later", "Consult with coworkers before taking any action"], "correctAnswer": 1, "explanation": "Observe, report, and call police to handle it."},
    {"question": "Stand your ground laws:", "options": ["Apply equally in all 50 states across the nation", "Vary by state - some have duty to retreat instead", "Only apply to law enforcement officers on duty", "Give security guards the same powers as police"], "correctAnswer": 1, "explanation": "Vary by state - some have duty to retreat instead."},
    {"question": "What are the three steps of STOP THE BLEED®?", "options": ["Call 911, apply bandage, wait for help", "Identify the bleeding, apply pressure, get help", "Assess scene, treat shock, call for backup", "Remove clothing, elevate limb, apply tourniquet"], "correctAnswer": 1, "explanation": "Identify the bleeding, apply pressure, get help."},
    {"question": "Where should a tourniquet be placed?", "options": ["Directly on the wound for maximum pressure", "2-3 inches above the wound, never on a joint", "As close to the body as possible", "On the joint closest to the wound"], "correctAnswer": 1, "explanation": "2-3 inches above the wound, never on a joint."},
    {"question": "Under the ADA, what questions can you ask about a service animal?", "options": ["What is your disability? and Can I see certification?", "Is this a service animal? and What task is it trained to perform?", "Where did you get the animal? and How much did it cost?", "You cannot ask any questions about service animals"], "correctAnswer": 1, "explanation": "Is this a service animal? and What task is it trained to perform?"},
    {"question": "What is racial profiling?", "options": ["A legal security technique based on statistics", "Basing security decisions on race alone - it is illegal", "A required practice for high-security venues", "Profiling only illegal if done by law enforcement"], "correctAnswer": 1, "explanation": "Basing security decisions on race alone - it is illegal."},
    {"question": "What is the first priority before providing medical care?", "options": ["Call 911 and get professional help", "Ensure scene safety for yourself and others", "Put on gloves and protective equipment", "Locate the source of bleeding"], "correctAnswer": 1, "explanation": "Ensure scene safety for yourself and others."},
    {"question": "How should you handle religious head coverings during screening?", "options": ["Always require removal for proper screening", "Respect them and screen without requiring removal when possible", "Only allow them with documentation", "Ask the person to prove their religion"], "correctAnswer": 1, "explanation": "Respect them and screen without requiring removal when possible."},
    {"question": "When using the radio, you should:", "options": ["Talk immediately after pressing the button", "Wait 1-2 seconds after pressing PTT before speaking", "Hold the button while listening", "Press and release quickly for each word"], "correctAnswer": 1, "explanation": "Wait 1-2 seconds after pressing PTT before speaking."},
    {"question": "What should you do if you witness discrimination?", "options": ["Ignore it unless the victim complains", "Intervene immediately, support victim, and report to supervisors", "Only get involved if it becomes violent", "Wait until your shift ends to mention it"], "correctAnswer": 1, "explanation": "Intervene immediately, support victim, and report to supervisors."},
    {"question": "Who can remove a tourniquet once applied?", "options": ["Anyone trained in STOP THE BLEED®", "Only medical professionals (EMS, doctors, nurses)", "The person who applied it if bleeding stopped", "A supervisor or team leader on scene"], "correctAnswer": 1, "explanation": "Only medical professionals (EMS, doctors, nurses)."}
]$$::jsonb,
total_questions = 42,
updated_at = NOW()
WHERE assessment_name LIKE '%Comprehensive%' OR assessment_name LIKE '%Final%' OR assessment_name LIKE '%Guard Certification%';

-- Verify the comprehensive assessment
SELECT 
    a.assessment_name,
    a.total_questions,
    jsonb_array_length(a.questions_json) as actual_questions,
    CASE 
        WHEN jsonb_array_length(a.questions_json) = a.total_questions THEN '✓ Match'
        ELSE '✗ Mismatch'
    END as status
FROM assessments a
WHERE a.assessment_name LIKE '%Comprehensive%' OR a.assessment_name LIKE '%Final%' OR a.assessment_name LIKE '%Guard Certification%';
